### ISSUE TITLE
cockiecutter fails on latest arch update

### ISSUE THREAD

**Issue by perlindgren** [robbert-vdh/nih-plug-template#1]
Steps to reproduce:

```shell
yay cookiecutter
cookiecutter gh:robbert-vdh/nih-plug-template
Traceback (most recent call last):
  File "/usr/bin/cookiecutter", line 5, in <module>
    from cookiecutter.__main__ import main
  File "/usr/lib/python3.10/site-packages/cookiecutter/__main__.py", line 2, in <module>
    from cookiecutter.cli import main
  File "/usr/lib/python3.10/site-packages/cookiecutter/cli.py", line 22, in <module>
    from cookiecutter.main import cookiecutter
  File "/usr/lib/python3.10/site-packages/cookiecutter/main.py", line 14, in <module>
    from cookiecutter.generate import generate_context, generate_files
  File "/usr/lib/python3.10/site-packages/cookiecutter/generate.py", line 11, in <module>
    from jinja2 import FileSystemLoader
  File "/home/pln/.local/lib/python3.10/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/pln/.local/lib/python3.10/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/pln/.local/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/pln/.local/lib/python3.10/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.10/site-packages/markupsafe/__init__.py)
```

Seems to be a problem with markupsafe.

Workaround:
```shell
pip install markupsafe==2.0.1
```

/Per

**Comment by robbert-vdh** [comment]
You should absolutely not be installing system wide dependencies using pip on Arch. Python packages should be installed from the repos using pacman.

And `python-cookiecutter-2.1.1-1` from the repos works just fine with `python-markupsafe-2.1.1-1` from the repos, since that's exactly what I'm using.
